version: '3.7'

services:
  web:
    image: hunnnys/web
  api:
    image: hunnnys/api
    environment:
    - DB_HOST=${DB_HOST}
    - DB_PORT=${DB_PORT}
    - MYSQL_USER=${MYSQL_USER}
    - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    - MYSQL_DATABASE=${MYSQL_DATABASE}
  db:
    image: postgres:16
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
  redis: 
    image: redis:latest
  data-modeling-api:
    image: yoonyounghun/fastapi