version: '3.7'

services:
  web:
    image: hunnnys/web:latest
  api:
    image: hunnnys/api:latest
    environment:
    - DB_HOST=${DB_HOST}
    - DB_PORT=${DB_PORT}
    - POSTGRES_USER=${POSTGRES_USER}
    - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    - REDIS_URL=${REDIS_URL}
    - SERVICE_KEY=${SERVICE_KEY}
    - FASTAPI_URL=${FASTAPI_URL}
  db:
    image: postgres:16
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
  redis: 
    image: redis:latest
  data-modeling-api:
    image: yoonyounghun/fastapi:latest
    environment:
      - BASE_URL=${BASE_URL}