services:
  api:
    ports:
      - 8000:8000
    networks:
      - app-net
    depends_on:
      - redis
      - db

  db:
    ports:
      - 5432:5432
    volumes:
      - ./postgresql/mount:/var/lib/postgresql/data
    networks:
      - app-net

  redis:
    ports:
      - 6379:6379
    networks:
      - app-net

  data-modeling-api:
    command: uvicorn main:app --host 0.0.0.0 --port 8001 --reload
    ports: 
      - 8001:8001
    depends_on:
      - db
      - redis
      - api
    networks:
      - app-net
  
networks:
  app-net:
    name: fingoo
