import type { Metadata } from 'next';
import './globals.css';
import MSWComponent from './ui/components/util/msw-component';
import { SWRProvider } from './ui/components/util/swr-provider';
import { cn } from './utils/style';
import localFont from 'next/font/local';
import ErrorBoundary from './ui/components/util/error-boundary';

const myFont = localFont({
  src: './PretendardVariable.woff2',
  display: 'swap',
  variable: '--font-pretendard',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html
      lang="kr"
      className="scrollbar-track-gray-300 scrollbar-thumb-fingoo-main scrollbar-track-rounded-full scrollbar-thumb-rounded-full"
    >
      <body className={cn(myFont.variable, 'font-pretendard')}>
        <ErrorBoundary>
          <MSWComponent>
            <SWRProvider>{children}</SWRProvider>
          </MSWComponent>
        </ErrorBoundary>
      </body>
    </html>
  );
}
