FROM python:3.9-slim AS builder

WORKDIR /code/data-modeling-api/

COPY ./ /code/data-modeling-api

RUN pip install --no-cache-dir -r /code/data-modeling-api/requirements.txt

FROM python:3.9-slim AS production

WORKDIR /code/data-modeling-api/

COPY --from=builder /usr/local/lib/python3.9/site-packages/ /usr/local/lib/python3.9/site-packages/
COPY --from=builder /usr/local/bin/ /usr/local/bin/
COPY --from=builder /code/data-modeling-api /code/data-modeling-api

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8001", "--reload"]