#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

npx lint-staged
if git diff --cached --name-only | grep -q "api"; then
  cd api && npm run test
elif git diff --cached --name-only | grep -q "web"; then
  cd web && npm run test
fi
