#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

commit_msg_file=$1
commit_msg=$(cat "$1")
second_line=$(echo "$commit_msg" | sed -n '2p')

if git diff --cached --name-only | grep -q "api"; then
  # api 경로가 포함되어 있으면, 해당 정보를 커밋 메시지에 추가
  commit_msg_title_regex='^(\[api\]\s*)(feat|fix|refactor|chore|test|docs|style): .{1,50}?$'
elif git diff --cached --name-only | grep -q "web"; then
   # web 경로가 포함되어 있으면, 해당 정보를 커밋 메시지에 추가
  commit_msg_title_regex='^(\[web\]\s*)(feat|fix|refactor|chore|test|docs|style): .{1,50}?$'
else
  commit_msg_title_regex='^(\[infra\]\s*)(feat|fix|refactor|chore|test|docs|style): .{1,50}?$'
fi


# 제목
if ! grep -qE "$commit_msg_title_regex" "$commit_msg_file"; then
  echo "COMMIT REJECTED: { [api|web|infra] feat|fix|refactor|chore|test|docs|style: commit 제목 } 제시된 형식에 맞게 작성해주세요."
  exit 1
fi

# 2번째 줄 -> 필요한가?
if ! [ -z "$second_line" ]; then
  echo "COMMIT REJECTED: 제목 아래 개행문자를 추가해주세요."
  exit 1
fi
