export const DIALOG_KEY = {
  METADATA_ROW_EDIT_MENU: 'METADATA_ROW_EDIT_MENU',
  METADATA_EDIT_MENU: 'METADATA_EDIT_MENU',
  METADATA_DELETE: 'METADATA_DELETE',
  INDICATOR_EDIT_MENU: 'INDICATOR_EDIT_MENU',
  CUSTOM_FORECAST_INDICATOR_EDIT_MENU: 'CUSTOM_FORECAST_INDICATOR_EDIT_MENU',
  CUSTOM_FORECAST_INDICATOR_CREATE_MENU: 'CUSTOM_FORECAST_INDICATOR_CREATE_MENU',
} as const;

export type DialogKey = (typeof DIALOG_KEY)[keyof typeof DIALOG_KEY];
