services:
  db:
    image: postgres:16
    ports:
      - '5432:5432'
    volumes:
      - ./postgresql/mount:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    networks:
      - api-net
    
  redis:
    image: redis:latest
    ports:
      - '6379:6379'
    networks:
      - api-net

  fastapi:
    image: hunnnys/fastapi:latest
    command: uvicorn main:app --host 0.0.0.0 --port 8001 --reload
    ports:
      - 8001:8001
    depends_on:
      - db
      - redis
    networks:
      - api-net
    extra_hosts:
      - host.docker.internal:host-gateway
    environment:
      - FAST_DB_HOST=${FAST_DB_HOST}
      - FAST_DB_PORT=${FAST_DB_PORT}
      - FAST_POSTGRES_USER=${FAST_POSTGRES_USER}
      - FAST_POSTGRES_PASSWORD=${FAST_POSTGRES_PASSWORD}
      - FAST_SERVICE_KEY=${FAST_SERVICE_KEY}
      - FAST_BASE_URL=${FAST_BASE_URL}

networks:
  api-net:
    name: fingoo-api
