services:
  db:
    image: postgres:16
    ports:
      - '5432:5432'
    volumes:
      - ./postgresql/mount:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    networks:
      - api-net
    
  redis:
    image: redis:latest
    ports:
      - '6379:6379'
    networks:
      - api-net

  fastapi:
    image: yoonyounghun/fastapi
    command: uvicorn main:app --host 0.0.0.0 --port 8001 --reload
    ports:
      - 8001:8001
    depends_on:
      - db
      - redis
    networks:
      - api-net
    extra_hosts:
      - host.docker.internal:host-gateway


networks:
  api-net:
    name: fingoo-api
