FROM node:20-alpine AS base

FROM base As Build
WORKDIR /api
COPY --chown=node:node package*.json ./
RUN npm ci
COPY --chown=node:node . .

RUN npm run build

ENV NODE_ENV production


RUN npm ci --only=production && npm cache clean --force

USER node

FROM base As Production

ENV NODE_ENV production

COPY --chown=node:node --from=build /api/node_modules ./node_modules
COPY --chown=node:node --from=build /api/dist ./dist

CMD [ "node", "dist/main.js" ]


