name: ci-cd-v2

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      tags:
        description: 'Test scenario tags'

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: setup
        run: echo "start build"

  build-web:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker Buildx for cache
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3.0.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Web build and push
        uses: docker/build-push-action@v5.1.0
        with:
          context: ./web
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/web:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

  build-api:
    runs-on: ubuntu-latest
    needs: setup
    env:
      NODE_ENV: build
      WORKDIR: api
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker Buildx for cache
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3.0.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.11.0'
      - name: Install dependencies
        run: npm ci
        working-directory: ${{ env.WORKDIR }}
      - name: Run tests
        run: npm test
        working-directory: ${{ env.WORKDIR }}

      - name: API build and push
        uses: docker/build-push-action@v5.1.0
        with:
          context: ./api
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/api:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
