name: ci-cd

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    name: build docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker Buildx for cache
        uses: docker/setup-buildx-action@v3
      - name: Login to Jira
        uses: atlassian/gajira-login@v3
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
      - name: Find Jira Issue Key in branch
        id: IssueKey
        uses: atlassian/gajira-find-issue-key@v3
        with:
          from: commits
      - name: Login to Docker Hub
        uses: docker/login-action@v3.0.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: API build and push
        uses: docker/build-push-action@v5.1.0
        with:
          context: ./api
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/api:latest
          # experiment for cache
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Web build and push
        uses: docker/build-push-action@v5.1.0
        with:
          context: ./web
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/web:latest
          # experiment for cache
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: E2E test for Acceptance Test
        run: docker compose -f docker-compose.yml -f docker-compose-build.yml up --abort-on-container-exit
      - name: Send discord message if fail
        if: ${{ failure() }}  
        uses: rjstone/discord-webhook-notify@v1.0.4
        with:
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK_URL }}
          severity: warn
          text: "build fail"
      - name: Transition Jira issue
        if: ${{ success() }}  
        uses: atlassian/gajira-transition@v3
        with:
          issue: ${{ steps.IssueKey.outputs.issue }}
          transitionId: 5
      - name: Send discord message if success
        if: ${{ success() }}  
        uses: rjstone/discord-webhook-notify@v1.0.4
        with:
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK_URL }}
          severity: info
          text: "build success"
