name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    name: build docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker Buildx for cache
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3.0.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: API build and push
        uses: docker/build-push-action@v5.1.0
        with:
          context: ./api
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/api:latest
          # experiment for cache
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Web build and push
        uses: docker/build-push-action@v5.1.0
        with:
          context: ./web
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/web:latest
          # experiment for cache
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: E2E test for Acceptance Test
        run: docker compose -f docker-compose.yml -f docker-compose-build.yml up --abort-on-container-exit